name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Setup GPG
        run: |
          # Create GPG configuration directory
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          
          # Configure GPG for batch mode
          cat > ~/.gnupg/gpg.conf << EOF
          use-agent
          pinentry-mode loopback
          batch
          yes
          EOF
          
          cat > ~/.gnupg/gpg-agent.conf << EOF
          allow-loopback-pinentry
          pinentry-program /usr/bin/pinentry-curses
          EOF
          
          # Kill any existing gpg-agent and start fresh
          pkill gpg-agent || true
          gpg-agent --daemon --allow-loopback-pinentry

      - name: Import GPG key
        run: |
          # Import the GPG private key
          echo "$SIGNING_KEY" | base64 --decode | gpg --batch --import --no-tty
          
          # Get the key ID (short format for signing)
          KEY_ID=$(gpg --list-secret-keys --keyid-format short --with-colons | grep '^sec' | cut -d: -f5 | head -1)
          
          if [[ -z "$KEY_ID" ]]; then
            echo "Error: Could not extract GPG key ID"
            gpg --list-secret-keys
            exit 1
          fi
          
          echo "SIGNING_KEY_ID=$KEY_ID" >> $GITHUB_ENV
          echo "Using GPG Key ID: $KEY_ID"
          
          # Verify key is available for signing
          gpg --list-secret-keys --keyid-format short
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v2

      - name: Build and Test
        run: ./gradlew clean build test --no-daemon --stacktrace

      - name: Publish to Maven Central Portal
        run: |
          ./gradlew publishAndReleaseToMavenCentral \
            --no-daemon \
            --no-parallel \
            --stacktrace \
            --info
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.CENTRAL_PORTAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.CENTRAL_PORTAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ env.SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}

      # Optional: Clean up GPG keys for security
      - name: Clean GPG Key
        if: always()
        run: |
          pkill gpg-agent || true
          rm -rf ~/.gnupg