name: Publish to Maven Central

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Import GPG key
        run: |
          echo "$SIGNING_KEY" | base64 --decode | gpg --batch --import
          gpg --list-secret-keys
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Publish to Maven Central
        run: ./gradlew clean publishReleasePublicationToSonatypeRepository --no-daemon --no-parallel --stacktrace
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}

      # Optional cleanup
      - name: Clean GPG Key (optional)
        if: always()
        run: |
          KEY_ID=$(gpg --list-secret-keys --with-colons | grep '^sec' | cut -d: -f5)
          if [[ ! -z "$KEY_ID" ]]; then
            gpg --batch --yes --delete-secret-keys "$KEY_ID"
          fi
